#ifndef _CPPRAYTRACERCHALLENGE_CORE_MATH_CONSTANTS
#define _CPPRAYTRACERCHALLENGE_CORE_MATH_CONSTANTS

namespace CppRayTracerChallenge::Core::Math
{
	const float EPSILON = 0.00001f;
}

#endif _CPPRAYTRACERCHALLENGE_CORE_MATH_CONSTANTS
